### PR TITLE
Update schema version to 1.6 and lucene version to 8.6

### PR DESCRIPTION
**Pull request by billdueber**
Makes parsing more efficient and eliminates deprecation warnings.

### CODE REVIEW

**Comment by jsteverman** [comment]
Why 8.6 and not 8.11?

**Comment by aelkiss** [comment]
8.11 may not be a valid Lucene schema version -- it doesn't go in lockstep with the Solr version. @billdueber will check.

If we need to make this change, then it should be merged to a separate branch for solr 8 (since presumably this won't be compatible with solr 6.). If it's possible to keep a single config until we're on solr 8 in production, then that would be preferable.

**Comment by billdueber** [comment]
For now I think we need to stick with 8.6; 8.7+ has changes to the default BM25 settings and (more importantly) to the way localparams are interpreted/allowed that we (I) dont' want to do deal with right now.

**Comment by aelkiss** [comment]
Subsumed by https://github.com/hathitrust/hathitrust_catalog_indexer/pull/13

**Pull request closed without merging**
